using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FIS.Models
{
    // Bill generated by FIS and sent to a customer when their order is shipped.
    // Replaces the broken manual process where salespeople forgot to bill customers.
    // Supports partial payments: BalanceRemaining reduces with each PaymentAR
    // until it reaches zero and Status becomes "Paid".
    public class CustomerBill
    {
        public int CustomerBillId { get; set; }

        // FK
        public int CustomerOrderId { get; set; }
        public int CustomerId { get; set; }

        public DateTime BillDate { get; set; } = DateTime.Now;
        public DateTime DueDate { get; set; }
        public decimal TotalAmountDue { get; set; }

        // Decremented with each partial or full payment
        // Case: "customers may submit a partial payment and this partial payment
        // should be recorded with the date it is received"
        public decimal BalanceRemaining { get; set; }

        // "Unpaid" | "PartiallyPaid" | "Paid" | "Overdue"
        public string Status { get; set; } = "Unpaid";

        // Navigation
        public CustomerOrder CustomerOrder { get; set; }
        public Customer Customer { get; set; }
        public List<PaymentAR> Payments { get; set; } = new List<PaymentAR>();
    }
}

