using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FIS.Models
{
    // Auto-generated by FIS when a RawMaterial's QuantityOnHand drops below ReorderThreshold.
    // Bills from vendors come to FIS and are recorded as InvoiceAP linked to this PO.
    public class PurchaseOrder
    {
        public int PurchaseOrderId { get; set; }

        // FK
        public int VendorId { get; set; }

        public DateTime OrderDate { get; set; } = DateTime.Now;
        public DateTime? ExpectedDeliveryDate { get; set; }
        public DateTime? ActualDeliveryDate { get; set; }

        public decimal TotalAmount { get; set; }

        // "Pending" | "Delivered" | "Cancelled"
        public string Status { get; set; } = "Pending";

        // Navigation
        public Vendor Vendor { get; set; }
        public List<PurchaseOrderItem> Items { get; set; } = new List<PurchaseOrderItem>();
        public InvoiceAP Invoice { get; set; }
    }
}